packages:
  - "!**/__test__/**"
  - "!**/__tests__/**"
  - "!**/__fixtures__/**"
  - "packages/**"
allowBuilds:
  nx: false
blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - tmp@0.2.6
  - chrono-node@2.2.4
  - lodash@4.17.23
  - yaml@2.8.3
  - lodash@4.17.24
  - brace-expansion@5.0.6
  - shell-quote@1.8.4
overrides:
  brace-expansion@>=5.0.0 <5.0.6: ^5.0.6
  chrono-node@<2.2.4: ^2.2.7
  lodash@<=4.17.23: ^4.17.24
  shell-quote@>=1.1.0 <=1.8.3: ^1.8.4
  tmp@<0.2.6: ^0.2.6
  yaml@>=2.0.0 <2.8.3: ^2.8.4
