packages:
  - "!**/__test__/**"
  - "!**/__tests__/**"
  - "!**/__fixtures__/**"
  - "packages/**"
allowBuilds:
  nx: false
blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - tmp@0.2.6
  - chrono-node@2.2.4
  - lodash@4.17.23
  - yaml@2.8.3
  - lodash@4.17.24
  - brace-expansion@5.0.6
  - shell-quote@1.8.4
overrides:
  brace-expansion@>=5.0.0 <5.0.6: ^5.0.7
  braces@<3.0.3: ">=3.0.3"
  chrono-node@<2.2.4: ^2.9.2
  form-data@>=4.0.0 <4.0.6: ">=4.0.6"
  lodash@<=4.17.23: ^4.17.24
  micromatch@<4.0.8: ">=4.0.8"
  shell-quote@>=1.1.0 <=1.8.3: ^1.10.0
  tmp@<0.2.6: ^0.2.7
  tmp@<=0.2.3: ">=0.2.7"
  tmp@>=0.2.6 <0.2.7: ">=0.2.7"
  undici@<6.27.0: ">=6.27.0"
  undici@>=7.0.0 <7.28.0: ">=7.28.0"
  "@actions/http-client>undici": ">=8.8.0"
  yaml@>=2.0.0 <2.8.3: ^2.9.0
