name: "Cleanup caches by a branch"

on: # yamllint disable-line rule:truthy
    pull_request:
        types:
            - "closed"
    workflow_dispatch: # yamllint disable-line rule:empty-values

jobs:
    cleanup-branch-cache:
        uses: "anolilab/workflows/.github/workflows/cleanup-branch-cache.yml@fbf35001fcbda1c67184c69f3695f06b963d377a" # main
        with:
            target-repo: "{{ ORGANIZATIONS }}/{{ REPOSITORY_NAME }}"
