name: "Cleanup caches by a branch"

on: # yamllint disable-line rule:truthy
    pull_request:
        types:
            - "closed"
    workflow_dispatch: # yamllint disable-line rule:empty-values

jobs:
    cleanup-branch-cache:
        uses: "anolilab/workflows/.github/workflows/cleanup-branch-cache.yml@d403f72a96c4b04c3d93ff1199c0787d544cd000" # v22.0.6
        with:
            target-repo: "{{ ORGANIZATIONS }}/{{ REPOSITORY_NAME }}"
