name: "Cleanup caches by a branch"

on: # yamllint disable-line rule:truthy
    pull_request:
        types:
            - "closed"
    workflow_dispatch: # yamllint disable-line rule:empty-values

jobs:
    cleanup-branch-cache:
        uses: "anolilab/workflows/.github/workflows/cleanup-branch-cache.yml@7aeab1cad9757c56df7e99a180b158a2e895984f" # main
        with:
            target-repo: "{{ ORGANIZATIONS }}/{{ REPOSITORY_NAME }}"
