name: "Lock inactive issues and pull requests"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch: # yamllint disable-line rule:empty-values

permissions:
    contents: "read"
    discussions: "write"
    issues: "write"
    pull-requests: "write"

jobs:
    lock-closed:
        uses: "anolilab/workflows/.github/workflows/lock-closed.yml@fbf35001fcbda1c67184c69f3695f06b963d377a" # main
        with:
            target-repo: "anolilab/monorepo-template"
