name: "Label Idle Issues"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 0 * * *"

jobs:
    stale-issues:
        uses: "anolilab/workflows/.github/workflows/stale-issues.yml@fbf35001fcbda1c67184c69f3695f06b963d377a" # main
        with:
            target-repo: "{{ ORGANIZATIONS }}/{{ REPOSITORY_NAME }}"
