name: "Label Idle Issues"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 0 * * *"

jobs:
    stale-issues:
        uses: "anolilab/workflows/.github/workflows/stale-issues.yml@7aeab1cad9757c56df7e99a180b158a2e895984f" # main
        with:
            target-repo: "{{ ORGANIZATIONS }}/{{ REPOSITORY_NAME }}"
